//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        public Block()
        {
            this.LawsuitBlocks = new HashSet<LawsuitBlock>();
            this.Parts = new HashSet<Part>();
        }
    
        public int BlockId { get; set; }
        public string BlockName { get; set; }
        public int BlockIncludeType { get; set; }
        public int BlockWeight { get; set; }
        public int BlockContentType { get; set; }
        public Nullable<int> FieldId { get; set; }
        public int GroupId { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<LawsuitBlock> LawsuitBlocks { get; set; }
        public virtual ICollection<Part> Parts { get; set; }
    }
}
