//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public Field()
        {
            this.Blocks = new HashSet<Block>();
        }
    
        public int FieldId { get; set; }
        public string FieldName { get; set; }
        public int FieldDataType { get; set; }
        public string FieldText { get; set; }
        public string FieldMarker { get; set; }
        public int FieldWeight { get; set; }
    
        public virtual ICollection<Block> Blocks { get; set; }
    }
}
