//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LawsuitBlock
    {
        public int RelationId { get; set; }
        public int LawsuitId { get; set; }
        public int BlockId { get; set; }
        public int LawsuitBlockWeight { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual Lawsuit Lawsuit { get; set; }
    }
}
