//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LawsuitDB : DbContext
    {
        public LawsuitDB()
            : base("name=LawsuitDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Block> Blocks { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Field> Fields { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<LawsuitBlock> LawsuitBlocks { get; set; }
        public DbSet<Lawsuit> Lawsuits { get; set; }
        public DbSet<Part> Parts { get; set; }
        public DbSet<SubCategory> SubCategories { get; set; }
        public DbSet<TextStyle> TextStyles { get; set; }
        public DbSet<WebResource> WebResources { get; set; }
    }
}
