//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lawsuit
    {
        public Lawsuit()
        {
            this.LawsuitBlocks = new HashSet<LawsuitBlock>();
        }
    
        public int LawsuitId { get; set; }
        public string LawsuitName { get; set; }
        public int SubCategoryId { get; set; }
        public int LawsuitWeight { get; set; }
        public Nullable<int> WebResourceId { get; set; }
    
        public virtual ICollection<LawsuitBlock> LawsuitBlocks { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual WebResource WebResource { get; set; }
    }
}
