//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int PartId { get; set; }
        public string PartName { get; set; }
        public string PartText { get; set; }
        public int TextStyleId { get; set; }
        public int PartWeight { get; set; }
        public int BlockId { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual TextStyle TextStyle { get; set; }
    }
}
