//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextStyle
    {
        public TextStyle()
        {
            this.Parts = new HashSet<Part>();
        }
    
        public int TextStyleId { get; set; }
        public string TextStyleName { get; set; }
        public int TextStyleWeight { get; set; }
        public int TextStyleTag { get; set; }
        public int TextStyleMarginLeft { get; set; }
        public int TextStyleTextAlign { get; set; }
        public bool TextStyleStong { get; set; }
        public bool TextStyleUnderline { get; set; }
        public bool TextStyleItalic { get; set; }
    
        public virtual ICollection<Part> Parts { get; set; }
    }
}
